In [87]:
# Importing libraries
# -------------------
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [88]:
#Importing the dataset
# ---------------------
dataset = pd.read_csv('/Users/vimalrajmatmari/Documents/Machine learning/Multiple-Linear-Dataset.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values

In [89]:
# Encoding categorical data
# -------------------------
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
columnTransformer = ColumnTransformer([('Location', OneHotEncoder(), [3])],remainder='passthrough')
X=np.array(columnTransformer.fit_transform(X))

In [90]:
# Avoiding the Dummy Variable Trap
X = X[:, 1:]

In [91]:
# Splitting the dataset into the Training set and Test set
# --------------------------------------------------------
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [92]:
# Fitting Multiple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression

In [93]:
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [94]:
# Predicting the Test set results
predictions = regressor.predict(X_test)
predictions

array([103015.20159794, 132582.27760818, 132447.73845176,  71976.09851256,
       178537.48221063, 116161.24230169,  67851.69209674,  98791.73374684,
       113969.43533016, 167921.06569557])

In [95]:
y_pred = regressor.predict(X_test)
y_pred

array([103015.20159794, 132582.27760818, 132447.73845176,  71976.09851256,
       178537.48221063, 116161.24230169,  67851.69209674,  98791.73374684,
       113969.43533016, 167921.06569557])

In [96]:
# Building the optimal model using Backward Elimination
import statsmodels.api as sm
X = np.append(arr=np.ones((50, 1)).astype(int), values=X, axis=1)
X_opt = np.array(X[:, [0, 1, 2, 3, 4, 5]], dtype=float)
regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Sun, 17 Sep 2023   Prob (F-statistic):           1.34e-27
Time:                        19:12:50   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.008e+04   6952.587      7.204      0.000    3.61e+04    6.41e+04
x1            41.8870   3256.039      0.013      0.990   -6520.229    6604.003
x2           240.6758   3338.857      0.072      0.943   -6488.349    6969.701
x3             0.8060      0.046     17.369      0.000       0.712       0.900
x4            -0.0270      0.052     -0.517      0.608      -0.132       0.078
x5             0.0270      0.017      1.574      0.123      -0.008       0.062
==============================================================================
Omnibus:                       14.782   Durbin-Watson:                   1.283
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.266
Skew:                          -0.948   Prob(JB):                     2.41e-05
Kurtosis:                       5.572   Cond. No.                     1.47e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.47e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [97]:
#X_opt = X[:, [0, 1, 3, 4, 5]]
X_opt = np.array(X[:, [0, 1, 3, 4, 5]], dtype=float)
regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     217.2
Date:                Sun, 17 Sep 2023   Prob (F-statistic):           8.51e-29
Time:                        19:13:27   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1070.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.016e+04   6798.992      7.377      0.000    3.65e+04    6.39e+04
x1           -70.2265   2828.752     -0.025      0.980   -5767.625    5627.172
x2             0.8057      0.046     17.646      0.000       0.714       0.898
x3            -0.0268      0.052     -0.520      0.606      -0.131       0.077
x4             0.0272      0.017      1.627      0.111      -0.006       0.061
==============================================================================
Omnibus:                       14.785   Durbin-Watson:                   1.281
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.242
Skew:                          -0.949   Prob(JB):                     2.44e-05
Kurtosis:                       5.568   Cond. No.                     1.44e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.44e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [67]:
#X_opt = X[:, [0, 3, 4, 5]]
X_opt = np.array(X[:, [0, 3, 4, 5]], dtype=float)
regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     296.0
Date:                Sun, 17 Sep 2023   Prob (F-statistic):           4.53e-30
Time:                        18:28:25   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      46   BIC:                             1066.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.012e+04   6572.353      7.626      0.000    3.69e+04    6.34e+04
x1             0.8057      0.045     17.846      0.000       0.715       0.897
x2            -0.0268      0.051     -0.526      0.602      -0.130       0.076
x3             0.0272      0.016      1.655      0.105      -0.006       0.060
==============================================================================
Omnibus:                       14.838   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.442
Skew:                          -0.949   Prob(JB):                     2.21e-05
Kurtosis:                       5.586   Cond. No.                     1.40e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [98]:
#X_opt = X[:, [0, 3, 5]]
X_opt = np.array(X[:, [0, 3, 5]], dtype=float)
regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     450.8
Date:                Sun, 17 Sep 2023   Prob (F-statistic):           2.16e-31
Time:                        19:13:46   Log-Likelihood:                -525.54
No. Observations:                  50   AIC:                             1057.
Df Residuals:                      47   BIC:                             1063.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.698e+04   2689.933     17.464      0.000    4.16e+04    5.24e+04
x1             0.7966      0.041     19.266      0.000       0.713       0.880
x2             0.0299      0.016      1.927      0.060      -0.001       0.061
==============================================================================
Omnibus:                       14.677   Durbin-Watson:                   1.257
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.161
Skew:                          -0.939   Prob(JB):                     2.54e-05
Kurtosis:                       5.575   Cond. No.                     5.32e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.32e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [99]:
#X_opt = X[:, [0, 3]]
X_opt = np.array(X[:, [0, 3]], dtype=float)
regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     849.8
Date:                Sun, 17 Sep 2023   Prob (F-statistic):           3.50e-32
Time:                        19:13:57   Log-Likelihood:                -527.44
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      48   BIC:                             1063.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.903e+04   2537.897     19.320      0.000    4.39e+04    5.41e+04
x1             0.8543      0.029     29.151      0.000       0.795       0.913
==============================================================================
Omnibus:                       13.727   Durbin-Watson:                   1.116
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               18.536
Skew:                          -0.911   Prob(JB):                     9.44e-05
Kurtosis:                       5.361   Cond. No.                     1.65e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.65e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [100]:
X = dataset.iloc[:, :-1:2].values
y = dataset.iloc[:, -1].values

In [101]:
X

array([[165349.2 , 471784.1 ],
       [162597.7 , 443898.53],
       [153441.51, 407934.54],
       [144372.41, 383199.62],
       [142107.34, 366168.42],
       [131876.9 , 362861.36],
       [134615.46, 127716.82],
       [130298.13, 323876.68],
       [120542.52, 311613.29],
       [123334.88, 304981.62],
       [101913.08, 229160.95],
       [100671.96, 249744.55],
       [ 93863.75, 249839.44],
       [ 91992.39, 252664.93],
       [119943.24, 256512.92],
       [114523.61, 261776.23],
       [ 78013.11, 264346.06],
       [ 94657.16, 282574.31],
       [ 91749.16, 294919.57],
       [ 86419.7 ,      0.  ],
       [ 76253.86, 298664.47],
       [ 78389.47, 299737.29],
       [ 73994.56, 303319.26],
       [ 67532.53, 304768.73],
       [ 77044.01, 140574.81],
       [ 64664.71, 137962.62],
       [ 75328.87, 134050.07],
       [ 72107.6 , 353183.81],
       [ 66051.52, 118148.2 ],
       [ 65605.48, 107138.38],
       [ 61994.48,  91131.24],
       [ 61136.38,  88218.23],
       [

In [102]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [103]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [104]:
y_pred = regressor.predict(X_test)

In [105]:
y_pred

array([126855.2361752 ,  82296.53163594,  97254.25284333,  46368.65783156,
       130089.77652378,  45938.44319255, 109289.06770923, 101151.02557555,
        96602.22391222, 112698.58543305, 128200.14138324, 170227.35281016,
        87437.66156335, 151341.85025263, 172650.42202302])

In [106]:
from sklearn import metrics
print('MAE:', metrics.mean_absolute_error(y_test, y_pred))
print('MSE:', metrics.mean_squared_error(y_test, y_pred))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

MAE: 6449.238325233511
MSE: 66537675.84655431
RMSE: 8157.062942417099


In [107]:
#Two input features (Product_3 and Location); 1 output represents the estimated profit based on these two features.
#-----------------------------------------------------------------------------------------------------------------
X = dataset.iloc[:, 2:-1].values
y = dataset.iloc[:, -1].values

In [108]:
X

array([[471784.1, 'City_1'],
       [443898.53, 'City_2'],
       [407934.54, 'City_3'],
       [383199.62, 'City_1'],
       [366168.42, 'City_3'],
       [362861.36, 'City_1'],
       [127716.82, 'City_2'],
       [323876.68, 'City_3'],
       [311613.29, 'City_1'],
       [304981.62, 'City_2'],
       [229160.95, 'City_3'],
       [249744.55, 'City_2'],
       [249839.44, 'City_3'],
       [252664.93, 'City_2'],
       [256512.92, 'City_3'],
       [261776.23, 'City_1'],
       [264346.06, 'City_2'],
       [282574.31, 'City_1'],
       [294919.57, 'City_3'],
       [0.0, 'City_1'],
       [298664.47, 'City_2'],
       [299737.29, 'City_1'],
       [303319.26, 'City_3'],
       [304768.73, 'City_3'],
       [140574.81, 'City_1'],
       [137962.62, 'City_2'],
       [134050.07, 'City_3'],
       [353183.81, 'City_1'],
       [118148.2, 'City_3'],
       [107138.38, 'City_1'],
       [91131.24, 'City_3'],
       [88218.23, 'City_1'],
       [46085.25, 'City_2'],
       [214634.81, 'C

In [109]:
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [110]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
columnTransformer = ColumnTransformer([('Location', OneHotEncoder(), [1])],remainder='passthrough')
X=np.array(columnTransformer.fit_transform(X))

In [111]:
X = X[:, 1:]

In [112]:
X

array([[0.0, 0.0, 471784.1],
       [1.0, 0.0, 443898.53],
       [0.0, 1.0, 407934.54],
       [0.0, 0.0, 383199.62],
       [0.0, 1.0, 366168.42],
       [0.0, 0.0, 362861.36],
       [1.0, 0.0, 127716.82],
       [0.0, 1.0, 323876.68],
       [0.0, 0.0, 311613.29],
       [1.0, 0.0, 304981.62],
       [0.0, 1.0, 229160.95],
       [1.0, 0.0, 249744.55],
       [0.0, 1.0, 249839.44],
       [1.0, 0.0, 252664.93],
       [0.0, 1.0, 256512.92],
       [0.0, 0.0, 261776.23],
       [1.0, 0.0, 264346.06],
       [0.0, 0.0, 282574.31],
       [0.0, 1.0, 294919.57],
       [0.0, 0.0, 0.0],
       [1.0, 0.0, 298664.47],
       [0.0, 0.0, 299737.29],
       [0.0, 1.0, 303319.26],
       [0.0, 1.0, 304768.73],
       [0.0, 0.0, 140574.81],
       [1.0, 0.0, 137962.62],
       [0.0, 1.0, 134050.07],
       [0.0, 0.0, 353183.81],
       [0.0, 1.0, 118148.2],
       [0.0, 0.0, 107138.38],
       [0.0, 1.0, 91131.24],
       [0.0, 0.0, 88218.23],
       [1.0, 0.0, 46085.25],
       [0.0, 1.0, 214

In [113]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [114]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [115]:
y_pred = regressor.predict(X_test)

In [116]:
from sklearn import metrics
print('MAE:', metrics.mean_absolute_error(y_test, y_pred))
print('MSE:', metrics.mean_squared_error(y_test, y_pred))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

MAE: 23260.91788950803
MSE: 762397073.5542035
RMSE: 27611.538775559096
